### PR TITLE
Adding support to read speakers

### PR DESCRIPTION
**Pull request by scandindian**
- Adding processor to read the data in open even format.
- Modifying manager to store the data.
- Modifying fragment to display the details.

With reference to this issue https://github.com/fossasia/connfa-android/issues/4

<table>
<td>

</td>
<td>

</td>
</table>

### CODE REVIEW

**Comment by scandindian** [comment]
@Shailesh351 @iamareebjamal @niranjan94 @the-dagger Please review.

**Review by iamareebjamal — APPROVED** [review]
Looks fine but I think not using a json parsing library will only make things hard for you. This can be error prone and compilcated

**Comment by scandindian** [comment]
Thanks for reviewing @iamareebjamal . Maybe I could use this https://github.com/jasminb/jsonapi-converter . It's also been used in open event android app. For now, I'll be adding this support to get the data in app first.

**Comment by mariobehling** [comment]
@heysadboy Why was this merged by yourself? Follow best practices! Don't merge your own commits!

**Comment by scandindian** [comment]
Sure @mariobehling, sorry about this. Won't be doing again.

**Pull request merged**
